const K='macarbox-stock-v1';
const defaultState=()=>({items:structuredClone(window.CATALOG),moves:[],orders:[],suppliers:[],requests:[],employees:[{id:'admin',name:'Administrateur',role:'Admin'}],machines:['FFG-970/2400'],settings:{currency:'CAD',company:'General Emballage',defaultMin:1,currentUser:'Administrateur'}});
let S=(()=>{try{return JSON.parse(localStorage.getItem(K))||defaultState()}catch(e){return defaultState()}})();
const firebaseConfig={apiKey:"AIzaSyBA0wdXAHmZg5wazDrxxbuGD1hrX-0iojU",authDomain:"general-emballage.firebaseapp.com",projectId:"general-emballage",storageBucket:"general-emballage.firebasestorage.app",messagingSenderId:"813924427671",appId:"1:813924427671:web:4914ad26f4a4a2e87e06d2",measurementId:"G-04Z1N77M9L"};
let cloud=null,auth=null,currentUser=null,currentProfile=null,cloudTimer=null,remoteApplying=false;
const COLS={items:'parts',moves:'movements',orders:'orders',suppliers:'suppliers',requests:'requests',employees:'users',machines:'machines'};
async function initCloud(){try{
 const [{initializeApp},{getFirestore,collection,doc,getDoc,getDocs,setDoc,deleteDoc,onSnapshot,writeBatch},{getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut,GoogleAuthProvider,signInWithPopup,signInWithRedirect}]=await Promise.all([
 import('https://www.gstatic.com/firebasejs/12.4.0/firebase-app.js'),
 import('https://www.gstatic.com/firebasejs/12.4.0/firebase-firestore.js'),
 import('https://www.gstatic.com/firebasejs/12.4.0/firebase-auth.js')]);
 let app=initializeApp(firebaseConfig);
 cloud={db:getFirestore(app),collection,doc,getDoc,getDocs,setDoc,deleteDoc,onSnapshot,writeBatch};
 auth={a:getAuth(app),onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut,GoogleAuthProvider,signInWithPopup,signInWithRedirect};
 auth.onAuthStateChanged(auth.a,async u=>{currentUser=u;currentProfile=null;if(u){await ensureProfile();await loadCloud();watchCloud()}updateAccount();nav();render()});
}catch(e){console.warn('Firebase',e);toast('Mode local')}}
async function ensureProfile(){
 let ref=cloud.doc(cloud.db,'users',currentUser.uid),snap=await cloud.getDoc(ref);
 if(snap.exists()){currentProfile=snap.data();return}
 let users=await cloud.getDocs(cloud.collection(cloud.db,'users'));
 let role='mecanicien';
 currentProfile={id:currentUser.uid,name:currentUser.displayName||currentUser.email,email:currentUser.email,role};
 await cloud.setDoc(ref,currentProfile);
}
async function loadCloud(){
 remoteApplying=true;
 for(const [key,col] of Object.entries(COLS)){let qs=await cloud.getDocs(cloud.collection(cloud.db,col));if(!qs.empty)S[key]=qs.docs.map(d=>({id:d.id,...d.data()}))}
 let cfg=await cloud.getDoc(cloud.doc(cloud.db,'settings','general'));if(cfg.exists())S.settings={...S.settings,...cfg.data()};
 localStorage.setItem(K,JSON.stringify(S));remoteApplying=false;
 if((await cloud.getDocs(cloud.collection(cloud.db,'parts'))).empty&&currentProfile?.role==='admin')await migrateSeed();
}
async function migrateSeed(){
 let batch=cloud.writeBatch(cloud.db),n=0;
 for(const x of S.items){batch.set(cloud.doc(cloud.db,'parts',String(x.id)),x);if(++n%400===0){await batch.commit();batch=cloud.writeBatch(cloud.db)}}
 await batch.commit();toast('Catalogue initial synchronisé');
}
function watchCloud(){
 Object.entries(COLS).forEach(([key,col])=>cloud.onSnapshot(cloud.collection(cloud.db,col),snap=>{if(snap.metadata.hasPendingWrites)return;remoteApplying=true;S[key]=snap.docs.map(d=>({id:d.id,...d.data()}));localStorage.setItem(K,JSON.stringify(S));remoteApplying=false;render()}));
 cloud.onSnapshot(cloud.doc(cloud.db,'settings','general'),s=>{if(s.exists()){S.settings={...S.settings,...s.data()};localStorage.setItem(K,JSON.stringify(S));render()}});
}
async function syncCollection(key){
 if(!cloud||!currentUser||remoteApplying)return;
 const col=COLS[key];if(!col)return;
 let remote=await cloud.getDocs(cloud.collection(cloud.db,col)),local=new Map((S[key]||[]).map(x=>[String(x.id),x]));
 let batch=cloud.writeBatch(cloud.db);
 remote.docs.forEach(d=>{if(!local.has(d.id))batch.delete(d.ref)});
 local.forEach((x,id)=>batch.set(cloud.doc(cloud.db,col,id),x));
 await batch.commit();
}
async function cloudSave(){
 if(!cloud||!currentUser||remoteApplying)return;
 clearTimeout(cloudTimer);cloudTimer=setTimeout(async()=>{try{
  for(const key of Object.keys(COLS))await syncCollection(key);
  await cloud.setDoc(cloud.doc(cloud.db,'settings','general'),S.settings,{merge:true});
 }catch(e){console.error(e);toast('Synchronisation refusée') }},300)
}
const save=()=>{localStorage.setItem(K,JSON.stringify(S));cloudSave();toast(currentUser?'Synchronisé':'Enregistré localement')}; const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(t){let x=$('#toast');x.textContent=t;x.style.display='block';setTimeout(()=>x.style.display='none',1200)}
const pages=[['dashboard','⌂ Accueil'],['stock','▦ Stock'],['scan','⌁ Scanner'],['requests','✦ Demandes'],['move','↕ Mouvements'],['orders','□ Commandes'],['inventory','✓ Inventaire'],['suppliers','◇ Fournisseurs'],['alerts','! Alertes'],['reports','▥ Rapports'],['team','♙ Employés'],['settings','⚙ Réglages'],['account','◉ Compte']]; let page='dashboard';
function allowedPage(p){let r=currentProfile?.role||'admin';return r==='mecanicien'?['account','dashboard','stock','scan','requests','reports'].includes(p):true}
function nav(){ $('#nav').innerHTML=pages.filter(p=>allowedPage(p[0])).map(p=>`<button class="${page==p[0]?'active':''}" data-p="${p[0]}">${p[1]}</button>`).join(''); document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{page=b.dataset.p;nav();render()}) }
const money=n=>new Intl.NumberFormat('fr-CA',{style:'currency',currency:S.settings.currency||'CAD'}).format(+n||0); const low=x=>(+x.qty||0)<=(+x.minQty||0);
function render(){({account,dashboard,stock,scan,requests,move,orders,inventory,suppliers,alerts,reports,team,settings}[page]||dashboard)()}
function updateAccount(){let b=document.querySelector('#accountState');if(b)b.textContent=currentUser?'☁️ '+(currentProfile?.role||'')+' · '+currentUser.email:'☁️ Connexion'}
function account(){if(currentUser){$('#app').innerHTML=`<h2>Compte</h2><div class="card"><b>${esc(currentUser.email)}</b> <span class="tag">${esc(currentProfile?.role||'')}</span><p class="muted">Connecté à la base General Emballage. Les modifications sont partagées entre les appareils connectés.</p><button class="btn" id="logout">Déconnexion</button></div>`;$('#logout').onclick=()=>auth.signOut(auth.a)}else{$('#app').innerHTML=`<h2>Connexion employés</h2><div class="card formgrid"><label>Courriel<input id="email" type="email" autocomplete="email"></label><label>Mot de passe<input id="pass" type="password" autocomplete="current-password"></label><div class="full"><button class="btn primary" id="login">Connexion</button> <button class="btn" id="signup">Créer le premier compte</button> <button class="btn" id="googleLogin">Continuer avec Google</button></div><p class="muted full">Active « Email/Password » dans Firebase Authentication avant la première connexion.</p></div>`;$('#login').onclick=async()=>{try{await auth.signInWithEmailAndPassword(auth.a,$('#email').value,$('#pass').value)}catch(e){alert('Connexion impossible : '+e.message)}};$('#signup').onclick=async()=>{try{await auth.createUserWithEmailAndPassword(auth.a,$('#email').value,$('#pass').value)}catch(e){alert('Création impossible : '+e.message)}};$('#googleLogin').onclick=async()=>{try{let p=new auth.GoogleAuthProvider();if(/iPhone|iPad|iPod/i.test(navigator.userAgent))await auth.signInWithRedirect(auth.a,p);else await auth.signInWithPopup(auth.a,p)}catch(e){alert('Connexion Google impossible : '+e.message)}}}}
function dashboard(){let total=S.items.reduce((a,x)=>a+(+x.qty||0),0), val=S.items.reduce((a,x)=>a+(+x.qty||0)*(+x.unitCost||0),0), lows=S.items.filter(low); $('#app').innerHTML=`<div class="grid"><div class="card metric"><span>Références catalogue</span><b>${S.items.length}</b></div><div class="card metric"><span>Unités en stock</span><b>${total}</b></div><div class="card metric"><span>Valeur du stock</span><b>${money(val)}</b></div><div class="card metric"><span>Alertes stock</span><b class="${lows.length?'bad':'ok'}">${lows.length}</b></div></div><div class="sectionTitle"><h2>À surveiller</h2><button class="btn primary" onclick="go('move')">Mouvement</button></div>${lows.slice(0,12).map(x=>`<div class="alert"><b>${esc(x.reference)}</b> — ${esc(x.description)}<br><span class="muted">${esc(x.category)} · Stock ${x.qty} · Minimum ${x.minQty}</span></div>`).join('')||'<div class="card">Aucune alerte.</div>'}`}
window.go=p=>{page=p;nav();render()};
function stock(){let cats=[...new Set(S.items.map(x=>x.category))],canEdit=currentProfile?.role!=='mecanicien'; $('#app').innerHTML=`<div class="toolbar"><input id="q" placeholder="Référence ou description"><select id="cat"><option value="">Toutes sections</option>${cats.map(c=>`<option>${esc(c)}</option>`).join('')}</select><select id="st"><option value="">Tous</option><option value="low">Stock bas</option><option value="spare">SPARE</option><option value="consumable">CONSUMMABLE</option></select>${canEdit?'<button class="btn primary" id="add">+ Ajouter pièce</button>':''}</div><div id="stocktable"></div>`; ['q','cat','st'].forEach(id=>$('#'+id).oninput=stockTable);if(canEdit)$('#add').onclick=()=>editItem();stockTable()}
window.viewPart=id=>{let x=S.items.find(i=>String(i.id)===String(id));if(!x)return;let canEdit=currentProfile?.role!=='mecanicien';let canMove=currentProfile?.role==='admin'||currentProfile?.role==='magasinier';$('#app').innerHTML=`<button class="btn" onclick="go('stock')">← Retour au stock</button><div class="partHero"><div class="partPhoto">${x.photoUrl?`<img src="${esc(x.photoUrl)}" alt="">`:'<div class="partPlaceholder">⚙<small>Photo de la pièce</small></div>'}</div><div class="partInfo"><span class="tag">${esc(x.category)}</span><h2>${esc(x.reference)}</h2><p class="partDesc">${esc(x.description)}</p><div class="partStats"><div><span>Stock</span><b class="${low(x)?'bad':'ok'}">${x.qty}</b></div><div><span>Minimum</span><b>${x.minQty}</b></div><div><span>Emplacement</span><b>${esc(x.location||'—')}</b></div><div><span>Type</span><b>${esc(x.type)}</b></div></div><div class="partActions">${canMove?`<button class="btn primary" onclick="quickMove('${x.id}')">↕ Entrée / sortie</button>`:''}<button class="btn" onclick="requestPart('${x.id}')">✦ Demander</button>${canEdit?`<button class="btn" onclick="editItem('${x.id}')">✎ Modifier</button>`:''}</div></div></div><div class="card partDetails"><h3>Détails</h3><div class="detailGrid"><div><span>Page catalogue</span><b>${esc(x.catalogPage||'—')}</b></div><div><span>Fournisseur</span><b>${esc(x.supplier||'—')}</b></div><div><span>Coût unitaire</span><b>${money(x.unitCost)}</b></div><div><span>Notes</span><b>${esc(x.notes||'—')}</b></div></div></div><h3>Derniers mouvements</h3>${movesTable(S.moves.filter(m=>String(m.itemId)===String(x.id)).slice().reverse().slice(0,12))}`}
window.requestPart=id=>{page='requests';nav();render();setTimeout(()=>{let s=$('#rqitem');if(s)s.value=id},0)};

function stockTable(){let q=($('#q')?.value||'').toLowerCase(),cat=$('#cat')?.value||'',st=$('#st')?.value||'';let a=S.items.filter(x=>(!q||(x.reference+' '+x.description).toLowerCase().includes(q))&&(!cat||x.category==cat)&&(!st||(st=='low'?low(x):x.type.toLowerCase()==st))); $('#stocktable').innerHTML=`<div class="tablewrap"><table><thead><tr><th>Référence</th><th>Description</th><th>Section</th><th>Type</th><th>Stock</th><th>Min.</th><th>Emplacement</th><th>Coût</th><th></th></tr></thead><tbody>${a.map(x=>`<tr class="${low(x)?'low':''}"><td><button class="partLink" onclick="viewPart('${x.id}')"><b>${esc(x.reference)}</b></button><br><span class="muted">Cat. p.${esc(x.catalogPage)}</span></td><td>${esc(x.description)}</td><td>${esc(x.category)}</td><td><span class="tag">${esc(x.type)}</span></td><td class="${low(x)?'bad':'ok'}">${x.qty}</td><td>${x.minQty}</td><td>${esc(x.location||'—')}</td><td>${money(x.unitCost)}</td><td class="rowactions">${currentProfile?.role!=='mecanicien'?`<button onclick="editItem('${x.id}')">✏️</button><button onclick="quickMove('${x.id}')">↕️</button>`:'Consultation'}</td></tr>`).join('')}</tbody></table></div>`}
window.editItem=id=>{if(currentProfile?.role==='mecanicien')return alert('Modification réservée au magasinier ou à l’administrateur');let x=id?S.items.find(i=>i.id==id):{id:'u-'+Date.now(),reference:'',description:'',category:'Autre',type:'SPARE',qty:0,minQty:S.settings.defaultMin||1,location:'',unitCost:0,supplier:'',notes:'',catalogPage:''}; $('#app').innerHTML=`<h2>${id?'Modifier':'Ajouter'} une pièce</h2><div class="card formgrid"><label>Référence<input id="fref" value="${esc(x.reference)}"></label><label>Description<input id="fdesc" value="${esc(x.description)}"></label><label>Section<input id="fcat" value="${esc(x.category)}"></label><label>Type<select id="ftype"><option ${x.type=='SPARE'?'selected':''}>SPARE</option><option ${x.type=='CONSUMMABLE'?'selected':''}>CONSUMMABLE</option></select></label><label>Stock actuel<input id="fqty" type="number" step="1" value="${x.qty}"></label><label>Stock minimum<input id="fmin" type="number" step="1" value="${x.minQty}"></label><label>Emplacement<input id="floc" value="${esc(x.location)}"></label><label>Coût unitaire<input id="fcost" type="number" step="0.01" value="${x.unitCost}"></label><label>Fournisseur<input id="fsup" value="${esc(x.supplier)}"></label><label>Page catalogue<input id="fpage" value="${esc(x.catalogPage)}"></label><label>Photo catalogue<input id="fphoto" value="${esc(x.photoUrl||'')}" placeholder="images/parts/reference.webp"></label><label class="full">Notes<textarea id="fnotes">${esc(x.notes)}</textarea></label><div class="full"><button class="btn primary" id="fsave">Enregistrer</button> <button class="btn" onclick="go('stock')">Annuler</button>${id?` <button class="btn" id="fdel">Supprimer</button>`:''}</div></div>`; $('#fsave').onclick=()=>{Object.assign(x,{reference:$('#fref').value.trim(),description:$('#fdesc').value.trim(),category:$('#fcat').value.trim(),type:$('#ftype').value,qty:+$('#fqty').value||0,minQty:+$('#fmin').value||0,location:$('#floc').value.trim(),unitCost:+$('#fcost').value||0,supplier:$('#fsup').value.trim(),catalogPage:$('#fpage').value.trim(),photoUrl:$('#fphoto').value.trim(),notes:$('#fnotes').value.trim()});if(!id)S.items.push(x);save();go('stock')}; if(id)$('#fdel').onclick=()=>{if(confirm('Supprimer cette pièce ?')){S.items=S.items.filter(i=>i.id!=id);save();go('stock')}}}
window.quickMove=id=>{page='move';nav();render();setTimeout(()=>{$('#mitem').value=id},0)};
function scan(){ $('#app').innerHTML=`<h2>Scanner une pièce</h2><div class="card"><p>Scanne un code-barres ou QR avec la caméra de l’iPhone. Le code peut être une référence du catalogue.</p><button class="btn primary" id="startscan">📷 Ouvrir la caméra</button><div id="scanbox" style="margin-top:12px"></div></div>`; $('#startscan').onclick=async()=>{if(!('BarcodeDetector'in window)){let code=prompt('Scanner non supporté ici. Entre la référence :');return code&&findScanned(code)};let box=$('#scanbox');box.innerHTML='<video id="cam" playsinline style="width:100%;max-width:520px;border-radius:12px"></video>';let v=$('#cam'),stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});v.srcObject=stream;await v.play();let d=new BarcodeDetector({formats:['qr_code','code_128','ean_13','ean_8','upc_a','upc_e']});let timer=setInterval(async()=>{try{let r=await d.detect(v);if(r[0]){clearInterval(timer);stream.getTracks().forEach(t=>t.stop());findScanned(r[0].rawValue)}}catch(e){}},400)}}
function findScanned(code){let x=S.items.find(i=>i.reference.toLowerCase()==String(code).trim().toLowerCase());if(x){page='stock';nav();render();setTimeout(()=>{let q=$('#q');if(q){q.value=x.reference;stockTable()}},0)}else alert('Référence non trouvée : '+code)}
function requests(){S.requests=S.requests||[];let canApprove=currentProfile?.role==='admin'||currentProfile?.role==='magasinier';let opts=S.items.map(x=>`<option value="${x.id}">${esc(x.reference)} — ${esc(x.description)}</option>`).join('');$('#app').innerHTML=`<h2>Demandes de pièces</h2><div class="card formgrid"><label>Pièce<select id="rqitem">${opts}</select></label><label>Quantité<input id="rqq" type="number" value="1" min="1"></label><label>Mécanicien<input id="rqu" value="${esc(S.settings.currentUser||'')}"></label><label>Machine<input id="rqm" value="FFG-970/2400"></label><label class="full">Motif<textarea id="rqn"></textarea></label><div><button class="btn primary" id="rqgo">Envoyer demande</button></div></div><h3>Demandes</h3>${S.requests.slice().reverse().map(r=>`<div class="card" style="margin-bottom:8px"><b>${esc(r.reference)}</b> × ${r.qty} · ${esc(r.user)} · ${esc(r.machine)}<br><span class="tag">${esc(r.status)}</span> <span class="muted">${esc(r.date)} ${esc(r.note||'')}</span>${r.status=='En attente'&&canApprove?`<div style="margin-top:8px"><button class="btn primary" onclick="approveRequest(${r.id})">Approuver & sortir</button> <button class="btn" onclick="rejectRequest(${r.id})">Refuser</button></div>`:''}</div>`).join('')||'<div class="card">Aucune demande.</div>'}`;$('#rqgo').onclick=()=>{let x=S.items.find(i=>i.id==$('#rqitem').value);S.requests.push({id:Date.now(),itemId:x.id,reference:x.reference,qty:+$('#rqq').value||1,user:currentUser?.email||$('#rqu').value,userId:currentUser?.uid||'',machine:$('#rqm').value,note:$('#rqn').value,status:'En attente',date:new Date().toISOString().slice(0,10)});save();render()}}
window.approveRequest=id=>{let r=S.requests.find(x=>x.id==id),x=S.items.find(i=>i.id==r.itemId);if(!x||x.qty<r.qty)return alert('Stock insuffisant');x.qty-=r.qty;r.status='Approuvée';S.moves.push({id:Date.now(),date:new Date().toISOString().slice(0,10),itemId:x.id,reference:x.reference,type:'out',qty:r.qty,doc:'DEM-'+r.id,user:r.user,machine:r.machine,note:r.note,balance:x.qty});save();render()};window.rejectRequest=id=>{let r=S.requests.find(x=>x.id==id);r.status='Refusée';save();render()}
function inventory(){let cats=[...new Set(S.items.map(x=>x.category))];$('#app').innerHTML=`<h2>Inventaire physique</h2><div class="card"><p class="muted">Choisis une section puis saisis le stock réellement compté. Chaque écart crée un ajustement traçable.</p><select id="invcat"><option value="">Toutes sections</option>${cats.map(x=>`<option>${esc(x)}</option>`).join('')}</select> <button class="btn primary" id="invload">Commencer</button></div><div id="invlist"></div>`;$('#invload').onclick=()=>{let a=S.items.filter(x=>!$('#invcat').value||x.category==$('#invcat').value);$('#invlist').innerHTML=`<div class="tablewrap"><table><tr><th>Référence</th><th>Théorique</th><th>Compté</th><th></th></tr>${a.map(x=>`<tr><td><b>${esc(x.reference)}</b><br>${esc(x.description)}</td><td>${x.qty}</td><td><input id="inv-${x.id}" type="number" value="${x.qty}" style="width:85px"></td><td><button onclick="countItem('${x.id}')">Valider</button></td></tr>`).join('')}</table></div>`}}
window.countItem=id=>{let x=S.items.find(i=>i.id==id),n=+$('#inv-'+id).value||0,old=x.qty;x.qty=n;S.moves.push({id:Date.now(),date:new Date().toISOString().slice(0,10),itemId:x.id,reference:x.reference,type:'adjust',qty:n,doc:'INVENTAIRE',user:S.settings.currentUser||'',note:'Écart '+(n-old),balance:n});save();render()}
function team(){
 S.employees=S.employees||[];
 $('#app').innerHTML='<div class="sectionTitle"><h2>Employés</h2></div><div class="card"><p class="muted">Chaque employé apparaît après sa première connexion. L’administrateur choisit ensuite son rôle.</p></div>'+
 S.employees.map(e=>'<div class="card" style="margin-top:8px"><b>'+esc(e.name||e.email)+'</b><br><span class="muted">'+esc(e.email||'')+'</span><div style="margin-top:8px"><select id="role-'+e.id+'"><option value="admin" '+(e.role==='admin'?'selected':'')+'>Admin</option><option value="magasinier" '+(e.role==='magasinier'?'selected':'')+'>Magasinier</option><option value="mecanicien" '+(e.role==='mecanicien'?'selected':'')+'>Mécanicien</option></select> <button class="btn" onclick="changeRole(\''+e.id+'\')">Enregistrer rôle</button></div></div>').join('');
}
window.changeRole=async id=>{
 if(currentProfile?.role!=='admin')return alert('Réservé à l’administrateur');
 let e=S.employees.find(x=>String(x.id)===String(id)); if(!e)return;
 e.role=$('#role-'+id).value;
 try{await cloud.setDoc(cloud.doc(cloud.db,'users',String(id)),e,{merge:true});toast('Rôle modifié')}
 catch(err){alert('Modification refusée : '+err.message)}
}
function move(){let opts=S.items.map(x=>`<option value="${x.id}">${esc(x.reference)} — ${esc(x.description)}</option>`).join('');$('#app').innerHTML=`<h2>Entrée / sortie de stock</h2><div class="card formgrid"><label>Pièce<select id="mitem">${opts}</select></label><label>Type<select id="mtype"><option value="in">Entrée</option><option value="out">Sortie / consommation</option><option value="adjust">Ajustement inventaire</option></select></label><label>Quantité<input id="mqty" type="number" min="0" step="1" value="1"></label><label>Date<input id="mdate" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Bon / demande / PO<input id="mref"></label><label>Utilisateur / technicien<input id="muser"></label><label class="full">Note<textarea id="mnote"></textarea></label><div class="full"><button class="btn primary" id="mgo">Confirmer</button></div></div><h2>Derniers mouvements</h2>${movesTable(S.moves.slice().reverse().slice(0,30))}`;$('#mgo').onclick=()=>{let x=S.items.find(i=>i.id==$('#mitem').value),t=$('#mtype').value,q=+$('#mqty').value||0;if(t=='out'&&q>x.qty&&!confirm('La sortie dépasse le stock. Continuer ?'))return;if(t=='in')x.qty+=q;else if(t=='out')x.qty-=q;else x.qty=q;S.moves.push({id:Date.now(),date:$('#mdate').value,itemId:x.id,reference:x.reference,type:t,qty:q,doc:$('#mref').value,user:$('#muser').value,note:$('#mnote').value,balance:x.qty});save();render()}}
function movesTable(a){return `<div class="tablewrap"><table><tr><th>Date</th><th>Référence</th><th>Type</th><th>Qté</th><th>Solde</th><th>Document</th><th>Employé / Machine</th></tr>${a.map(m=>`<tr><td>${esc(m.date)}</td><td>${esc(m.reference)}</td><td>${m.type}</td><td>${m.qty}</td><td>${m.balance}</td><td>${esc(m.doc||'')}</td><td>${esc(m.user||'')} ${m.machine?'· '+esc(m.machine):''}</td></tr>`).join('')}</table></div>`}
function orders(){ $('#app').innerHTML=`<div class="sectionTitle"><h2>Commandes fournisseurs</h2><button class="btn primary" id="newpo">+ Nouvelle commande</button></div>${S.orders.length?`<div class="tablewrap"><table><tr><th>PO</th><th>Date</th><th>Fournisseur</th><th>Référence</th><th>Qté</th><th>Prix</th><th>Statut</th><th></th></tr>${S.orders.slice().reverse().map(o=>`<tr><td>${esc(o.po)}</td><td>${esc(o.date)}</td><td>${esc(o.supplier)}</td><td>${esc(o.reference)}</td><td>${o.qty}</td><td>${money(o.price)}</td><td>${esc(o.status)}</td><td><button onclick="receivePO(${o.id})">Réception</button></td></tr>`).join('')}</table></div>`:'<div class="card">Aucune commande.</div>'}`;$('#newpo').onclick=newPO}
function newPO(){let opts=S.items.map(x=>`<option value="${x.id}">${esc(x.reference)} — ${esc(x.description)}</option>`).join('');$('#app').innerHTML=`<h2>Nouvelle commande</h2><div class="card formgrid"><label>No PO<input id="po" value="PO-${new Date().getFullYear()}-${String(S.orders.length+1).padStart(3,'0')}"></label><label>Date<input id="pod" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Fournisseur<input id="pos"></label><label>Pièce<select id="poi">${opts}</select></label><label>Quantité<input id="poq" type="number" value="1"></label><label>Prix unitaire<input id="pop" type="number" step="0.01"></label><label>Statut<select id="post"><option>À commander</option><option>Commandée</option><option>Partielle</option><option>Reçue</option></select></label><label class="full">Note<textarea id="pon"></textarea></label><div><button class="btn primary" id="posave">Enregistrer</button></div></div>`;$('#posave').onclick=()=>{let x=S.items.find(i=>i.id==$('#poi').value);S.orders.push({id:Date.now(),po:$('#po').value,date:$('#pod').value,supplier:$('#pos').value,itemId:x.id,reference:x.reference,qty:+$('#poq').value||0,price:+$('#pop').value||0,status:$('#post').value,note:$('#pon').value});save();go('orders')}}
window.receivePO=id=>{let o=S.orders.find(x=>x.id==id),x=S.items.find(i=>i.id==o.itemId);if(!x)return;let q=+(prompt('Quantité reçue',o.qty)||0);if(q){x.qty+=q;o.status=q>=o.qty?'Reçue':'Partielle';S.moves.push({id:Date.now(),date:new Date().toISOString().slice(0,10),itemId:x.id,reference:x.reference,type:'in',qty:q,doc:o.po,user:'',note:'Réception commande',balance:x.qty});save();render()}}
function suppliers(){ $('#app').innerHTML=`<div class="sectionTitle"><h2>Fournisseurs</h2><button class="btn primary" id="adds">+ Ajouter</button></div>${S.suppliers.map(s=>`<div class="card" style="margin-bottom:8px"><b>${esc(s.name)}</b><div class="muted">${esc(s.contact||'')} ${esc(s.email||'')} ${esc(s.phone||'')}</div></div>`).join('')||'<div class="card">Aucun fournisseur enregistré.</div>'}`;$('#adds').onclick=()=>{let name=prompt('Nom du fournisseur');if(!name)return;S.suppliers.push({id:Date.now(),name,contact:prompt('Contact')||'',email:prompt('Courriel')||'',phone:prompt('Téléphone')||''});save();render()}}
function alerts(){let a=S.items.filter(low).sort((x,y)=>(x.qty-x.minQty)-(y.qty-y.minQty));$('#app').innerHTML=`<h2>Alertes de réapprovisionnement</h2>${a.map(x=>`<div class="alert"><b>${esc(x.reference)}</b> — ${esc(x.description)}<br>Stock: <b>${x.qty}</b> / minimum ${x.minQty} · à commander: <b>${Math.max(0,x.minQty*2-x.qty)}</b> · ${esc(x.location||'emplacement non défini')}</div>`).join('')||'<div class="card">Tout est au-dessus du minimum.</div>'}`}
function reports(){let val=S.items.reduce((a,x)=>a+x.qty*x.unitCost,0),cons={};S.moves.filter(m=>m.type=='out').forEach(m=>cons[m.reference]=(cons[m.reference]||0)+(+m.qty||0));let top=Object.entries(cons).sort((a,b)=>b[1]-a[1]).slice(0,10);$('#app').innerHTML=`<h2>Rapports & sauvegarde</h2><div class="grid"><div class="card metric"><span>Valeur stock</span><b>${money(val)}</b></div><div class="card metric"><span>Mouvements</span><b>${S.moves.length}</b></div><div class="card metric"><span>Commandes ouvertes</span><b>${S.orders.filter(o=>o.status!='Reçue').length}</b></div></div><div class="card" style="margin-top:12px"><h3>Export / import</h3><p class="muted">Sauvegarde complète sur ton téléphone/ordinateur. Le fichier JSON restaure tout.</p><button class="btn primary" onclick="exportJSON()">Exporter sauvegarde JSON</button> <button class="btn" onclick="exportCSV()">Exporter stock CSV</button> <label class="btn">Importer JSON<input id="imp" type="file" accept="application/json" hidden></label></div><h3>Pièces les plus consommées</h3><div class="card">${top.map(([r,q])=>`<div><b>${esc(r)}</b> — ${q} unité(s)</div>`).join('')||'Pas encore de consommation.'}</div><h3>Historique : qui a pris quoi</h3>${movesTable(S.moves.slice().reverse())}`;$('#imp').onchange=e=>{let f=e.target.files[0],r=new FileReader();r.onload=()=>{try{S=JSON.parse(r.result);save();render()}catch(e){alert('Fichier invalide')}};r.readAsText(f)}}
function dl(name,text,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
window.exportJSON=()=>dl('stock-macarbox-backup.json',JSON.stringify(S,null,2),'application/json');window.exportCSV=()=>{let rows=[['Reference','Description','Section','Type','Stock','Minimum','Emplacement','Cout']].concat(S.items.map(x=>[x.reference,x.description,x.category,x.type,x.qty,x.minQty,x.location,x.unitCost]));dl('stock-macarbox.csv',rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv')}
function settings(){ $('#app').innerHTML=`<h2>Réglages</h2><div class="card formgrid"><label>Entreprise<input id="setco" value="${esc(S.settings.company||'')}"></label><label>Devise<select id="setcur"><option ${S.settings.currency=='CAD'?'selected':''}>CAD</option><option ${S.settings.currency=='EUR'?'selected':''}>EUR</option><option ${S.settings.currency=='USD'?'selected':''}>USD</option></select></label><label>Minimum par défaut<input id="setmin" type="number" value="${S.settings.defaultMin||1}"></label><div class="full"><button class="btn primary" id="setsave">Enregistrer</button> <button class="btn" id="resetcat">Réinitialiser catalogue</button></div></div><div class="card" style="margin-top:12px"><b>Catalogue chargé:</b> FFG-970/2400 #196 · Issue 04/2020<br><span class="muted">${S.items.length} lignes de pièces, sections mécaniques A1–A6/A3.1 et électriques B1–B7.</span></div>`;$('#setsave').onclick=()=>{S.settings={company:$('#setco').value,currency:$('#setcur').value,defaultMin:+$('#setmin').value||1};save();render()};$('#resetcat').onclick=()=>{if(confirm('Réinitialiser les pièces du catalogue ? Les mouvements et commandes restent.')){let old=new Map(S.items.map(x=>[x.category+'|'+x.reference,x]));S.items=structuredClone(window.CATALOG).map(x=>Object.assign(x,old.get(x.category+'|'+x.reference)||{}));save();render()}}}
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$('#installBtn').hidden=true}};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');nav();render();initCloud();
